[package]
name = "discv5"
authors = ["Age Manning <Age@AgeManning.com>"]
edition = "2018"
version = "0.1.0-alpha.12"
description = "Implementation of the p2p discv5 discovery protocol"
license = "MIT"
repository = "https://github.com/sigp/discv5"
readme = "./README.md"
keywords = ["peer-to-peer", "libp2p", "networking", "discovery", "discv5"]
categories = ["network-programming", "asynchronous"]
exclude = [
	".gitignore",
	".github/*"
]

[dependencies]
enr = { version = "0.3.0", features = ["libsecp256k1", "ed25519"] }
tokio = { version = "0.2.22", features = ["net", "stream", "time", "sync"] }
zeroize = { version = "1.1.0", features = ["zeroize_derive"] }
libp2p-core = { version = "0.22.1", optional = true }
multihash = { version = "0.11.2", optional = true }
libsecp256k1 = "0.3.5"
futures = "0.3.5"
uint = { version = "0.8.3", default-features = false }
log = "0.4.11"
rlp = "0.4.5"
sha2 = "0.8.1"
hkdf = "0.8.0"
hex = "0.4.2"
fnv = "1.0.7"
arrayvec = "0.5.1"
digest = "0.8.1"
rand = "0.7.3"
smallvec = "1.4.1"
parking_lot = "0.11.0"
lru_time_cache = "0.10.0"
lazy_static = "1.4.0"
aes-gcm = "0.6.0"
socket2 = "0.3.12"

[dev-dependencies]
quickcheck = "0.9.2"
env_logger = "0.7.1"
hex-literal = "0.3.0"
simple_logger = "1.6.0"
tokio = { version = "0.2.22", features = ["time", "rt-threaded", "macros"] }
rand_xorshift = "0.2.0"
rand_core = "0.5.1"

[features]
libp2p = ["libp2p-core", "multihash"]
